### ISSUE TITLE
Search in forums / messages

### ISSUE THREAD

**Issue by david-devolute** [Restream/redmine_elasticsearch#39]
In Redmine 3.x and the latest `redmine_elasticsearch` it's not possible to search in forums/messages. It's because the `_parent` attribute is not set correctly in `MessageSerializer`.

See #38 for a quick fix.

It would be nice to mention in the README if Redmine 3.x is supported or not. I was able to use it with Redmine 3.2.2 (Rails 4.2) and ES 1.7.3.

**Comment by nodecarter** [comment]
Fixed this in 0.2.0 version
