### ISSUE TITLE
Issue when running plugin

### ISSUE THREAD

**Issue by frogec** [Restream/redmine_elasticsearch#42]
Hi, 

i've tried this plugin and I think it's a great idea.

I have a problem when running this plugin. I tried master and 0.2.0 version.
After step 6, `bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production`, I got this error.

![screenshot_66](https://cloud.githubusercontent.com/assets/15109727/23454408/6b5e059c-fe6c-11e6-880a-285d9e2d2de9.png)

I'v corrected line in search_controller_patch.rb, line 204,  from 

def get_search_fields(titles_only:, search_attachments:)

to 

`def get_search_fields(titles_only, search_attachments)`

I've successfully reindexed document in Elasticsearch with version 0.2.0 but not with master. 

Master gives me error in, index.rake, line 68.

`estimated_records = ParentProject.count`

ParentProject not initialized.

Thank you,
Nejc

**Comment by nodecarter** [comment]
Hi @frogec , 
I think you got this error because you are use old ruby. 
And I can not guarantee that this plugin will work on Windows.

**Comment by frogec** [comment]
Yes, it was a problem with old version of ruby. I've got it to work by updating ruby/redmine by using latest Bitnami redmine-3.3.2-2. And all this is working on windows and for now no problems.

I'm closing the issue.
